<a href="https://colab.research.google.com/github/gaganchapa/Pytorch/blob/main/Pytorch_Logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# 0) Prepare data
data = datasets.load_breast_cancer()
X, y = data.data, data.target

In [53]:
X.shape

(569, 30)

In [54]:
n_samples, n_features = X.shape

Splitting the data

In [55]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)
X_train

array([[1.288e+01, 1.822e+01, 8.445e+01, ..., 1.096e-01, 2.582e-01,
        8.893e-02],
       [1.113e+01, 2.244e+01, 7.149e+01, ..., 6.413e-02, 3.169e-01,
        8.032e-02],
       [1.263e+01, 2.076e+01, 8.215e+01, ..., 1.105e-01, 2.226e-01,
        8.486e-02],
       ...,
       [1.247e+01, 1.860e+01, 8.109e+01, ..., 1.015e-01, 3.014e-01,
        8.750e-02],
       [1.822e+01, 1.870e+01, 1.203e+02, ..., 1.325e-01, 3.021e-01,
        7.987e-02],
       [1.272e+01, 1.378e+01, 8.178e+01, ..., 6.343e-02, 2.369e-01,
        6.922e-02]])

In [56]:

# scale
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train

array([[-0.36180827, -0.26521011, -0.31715702, ..., -0.07967528,
        -0.52798733,  0.2506337 ],
       [-0.8632675 ,  0.71560604, -0.85646012, ..., -0.76980239,
         0.44312729, -0.20987332],
       [-0.4334453 ,  0.32513895, -0.41286667, ..., -0.06601541,
        -1.1169427 ,  0.0329492 ],
       ...,
       [-0.479293  , -0.17689018, -0.45697634, ..., -0.20261414,
         0.18670009,  0.17414996],
       [ 1.16835876, -0.15364809,  1.17466524, ...,  0.26789258,
         0.19828067, -0.23394164],
       [-0.40765597, -1.29715887, -0.42826344, ..., -0.78042674,
        -0.88036793, -0.80355834]])

Converting Numpy to Torch Tensor

In [57]:
X_train = torch.from_numpy(X_train.astype(np.float32))
X_test = torch.from_numpy(X_test.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))
X_train

tensor([[-0.3618, -0.2652, -0.3172,  ..., -0.0797, -0.5280,  0.2506],
        [-0.8633,  0.7156, -0.8565,  ..., -0.7698,  0.4431, -0.2099],
        [-0.4334,  0.3251, -0.4129,  ..., -0.0660, -1.1169,  0.0329],
        ...,
        [-0.4793, -0.1769, -0.4570,  ..., -0.2026,  0.1867,  0.1741],
        [ 1.1684, -0.1536,  1.1747,  ...,  0.2679,  0.1983, -0.2339],
        [-0.4077, -1.2972, -0.4283,  ..., -0.7804, -0.8804, -0.8036]])

In [58]:
y_train.shape

torch.Size([455])

In [59]:
y_train

tensor([1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1.,
        0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
        1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1.,
        1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0.,
        1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0.,
        1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
        0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
        0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
        0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.,
        0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
        1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0.,
        1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
        1., 1., 1., 0., 1., 1., 1., 0., 

Converting target variables to 1d format

In [60]:
y_train = y_train.view(y_train.shape[0], 1)
y_test = y_test.view(y_test.shape[0], 1)
y_train.shape

torch.Size([455, 1])

In [61]:

# 1) Model
# Linear model f = wx + b , sigmoid at the end
class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features, 1)

    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred

model = Model(n_features)

In [62]:


# 2) Loss and optimizer
num_epochs = 100
learning_rate = 0.01
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# 3) Training loop
for epoch in range(num_epochs):
    # Forward pass and loss
    y_pred = model(X_train)
    loss = criterion(y_pred, y_train)

    # Backward pass and update
    loss.backward()
    optimizer.step()

    # zero grad before new step
    optimizer.zero_grad()

    if (epoch+1) % 10 == 0:
        print(f'epoch: {epoch+1}, loss = {loss.item():.4f}')


with torch.no_grad():
    y_predicted = model(X_test)
    y_predicted_cls = y_predicted.round()
    acc = y_predicted_cls.eq(y_test).sum() / float(y_test.shape[0])
    print(f'accuracy: {acc.item():.4f}')

epoch: 10, loss = 0.5619
epoch: 20, loss = 0.4647
epoch: 30, loss = 0.4030
epoch: 40, loss = 0.3601
epoch: 50, loss = 0.3282
epoch: 60, loss = 0.3034
epoch: 70, loss = 0.2834
epoch: 80, loss = 0.2670
epoch: 90, loss = 0.2531
epoch: 100, loss = 0.2413
accuracy: 0.9035
